# This is a basic workflow to help you get started with Actions

name: Deploy to App Engine

on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Deploy to App Engine
        id: deploy
        uses: google-github-actions/deploy-appengine@main
        with:
          deliverables: app.yaml
          project_id: ${{ secrets.project_id }}
          credentials: ${{ secrets.GCP_SA_KEY }}
  
      - name: Test and Show Output
        id: test
        run: |
          curl "${{ steps.deploy.outputs.url }}"
          echo "${{ steps.deploy.outputs.url }}"

          
