# This is a basic workflow to help you get started with Actions

name: Deploy to App Engine

on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Build Web App
        run: npm run build
        
      - name: Deploy an App Engine app
        id: deploy
        uses: google-github-actions/deploy-appengine@main
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          deliverables: app.yaml
          credentials: ${{ secrets.GCP_SA_KEY }}
        
#       - name: Deploy Web App
#         run: gcloud app deploy --project=${{ secrets.GCP_PROJECT }}
      
#       - name: Deploy to App Engine
#         id: deploy
#         uses: google-github-actions/deploy-appengine@main
#         with:
#           project_id: ${{ secrets.project_id }}
#           credentials: ${{ secrets.GCP_SA_KEY }}
  
      - name: Test and Show Status Code
        id: test
        run: curl -o /dev/null --silent --head --write-out '%{http_code}\n' ${{ steps.deploy.outputs.url }}

          
